# Generated by Django 5.2.1 on 2025-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slangify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slang',
            name='cultural_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='slang',
            name='trendiness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slang',
            name='usage_example',
            field=models.TextField(blank=True),
        ),
    ]
